export const ORDER_STATUSES = Object.freeze({
  PENDING: 'pending',
  PAYMENT_RETRY: 'payment_retry',
  ACCEPTED: 'accepted',
  PREPARING: 'preparing',
  READY_FOR_PICKUP: 'ready_for_pickup',
  LEGACY_PROCESSING: 'processing',
  PICKED_UP: 'picked_up',
  DELIVERING: 'delivering',
  COMPLETED: 'completed',
  REJECTED: 'rejected'
});

export const ORDER_STATUS_VALUES = Object.freeze(Object.values(ORDER_STATUSES));

export const SELLER_ORDER_STATUS_VALUES = Object.freeze([
  ORDER_STATUSES.ACCEPTED,
  ORDER_STATUSES.PREPARING,
  ORDER_STATUSES.READY_FOR_PICKUP,
  ORDER_STATUSES.REJECTED,
  ORDER_STATUSES.PAYMENT_RETRY
]);

export const SHIPPER_ORDER_STATUS_VALUES = Object.freeze([
  ORDER_STATUSES.PICKED_UP,
  ORDER_STATUSES.DELIVERING,
  ORDER_STATUSES.COMPLETED
]);

export const SHIPPER_READY_STATUS_VALUES = Object.freeze([
  ORDER_STATUSES.READY_FOR_PICKUP,
  ORDER_STATUSES.LEGACY_PROCESSING
]);

export const ACTIVE_ORDER_STATUS_VALUES = Object.freeze([
  ORDER_STATUSES.PENDING,
  ORDER_STATUSES.PAYMENT_RETRY,
  ORDER_STATUSES.ACCEPTED,
  ORDER_STATUSES.PREPARING,
  ORDER_STATUSES.READY_FOR_PICKUP,
  ORDER_STATUSES.LEGACY_PROCESSING,
  ORDER_STATUSES.PICKED_UP,
  ORDER_STATUSES.DELIVERING
]);

export const IN_PROGRESS_ORDER_STATUS_VALUES = Object.freeze([
  ORDER_STATUSES.ACCEPTED,
  ORDER_STATUSES.PREPARING,
  ORDER_STATUSES.READY_FOR_PICKUP,
  ORDER_STATUSES.LEGACY_PROCESSING,
  ORDER_STATUSES.PICKED_UP,
  ORDER_STATUSES.DELIVERING
]);

export const ACTIVE_SHIPPER_ORDER_STATUS_VALUES = Object.freeze([
  ORDER_STATUSES.PICKED_UP,
  ORDER_STATUSES.DELIVERING
]);

export const REJECTED_ORDER_STATUS_VALUES = Object.freeze([
  ORDER_STATUSES.REJECTED
]);

export const COMPLETED_ORDER_STATUS = ORDER_STATUSES.COMPLETED;
